using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Obviously.SemanticTypes.Generator
{
    // ReSharper disable once UnusedMember.Global, reason: utilized by the roslyn code generator
    public partial class SemanticTypeGenerator
    {
        private static (SimpleBaseTypeSyntax? baseType, IEnumerable<MemberDeclarationSyntax> members) GenerateEquality(string actualTypeFullName, string identifier)
        {
            var baseType = SimpleBaseType(
                GenericName(
                        Identifier("IEquatable"))
                    .WithTypeArgumentList(
                        TypeArgumentList(
                            SingletonSeparatedList<TypeSyntax>(
                                IdentifierName(identifier)))));
            var members =
                List(
                    new MemberDeclarationSyntax[]
                    {
                        MethodDeclaration(
                                PredefinedType(
                                    Token(SyntaxKind.BoolKeyword)),
                                Identifier("Equals"))
                            .WithModifiers(
                                TokenList(
                                    Token(SyntaxKind.PublicKeyword)))
                            .WithParameterList(
                                ParameterList(
                                    SingletonSeparatedList(
                                        Parameter(
                                                Identifier("other"))
                                            .WithType(
                                                IdentifierName(identifier)))))
                            .WithBody(
                                Block(
                                    IfStatement(
                                        IsPatternExpression(
                                            IdentifierName("other"),
                                            ConstantPattern(
                                                LiteralExpression(
                                                    SyntaxKind.NullLiteralExpression))),
                                        ReturnStatement(
                                            LiteralExpression(
                                                SyntaxKind.FalseLiteralExpression))),
                                    IfStatement(
                                        InvocationExpression(
                                                IdentifierName("ReferenceEquals"))
                                            .WithArgumentList(
                                                ArgumentList(
                                                    SeparatedList<ArgumentSyntax>(
                                                        new SyntaxNodeOrToken[]
                                                        {
                                                            Argument(
                                                                ThisExpression()),
                                                            Token(SyntaxKind.CommaToken),
                                                            Argument(
                                                                IdentifierName("other"))
                                                        }))),
                                        ReturnStatement(
                                            LiteralExpression(
                                                SyntaxKind.TrueLiteralExpression))),
                                    ReturnStatement(
                                        BinaryExpression(
                                            SyntaxKind.EqualsExpression,
                                            IdentifierName("_value"),
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("other"),
                                                IdentifierName("_value")))))),
                        MethodDeclaration(
                                PredefinedType(
                                    Token(SyntaxKind.BoolKeyword)),
                                Identifier("Equals"))
                            .WithModifiers(
                                TokenList(
                                    new[]
                                    {
                                        Token(SyntaxKind.PublicKeyword),
                                        Token(SyntaxKind.OverrideKeyword)
                                    }))
                            .WithParameterList(
                                ParameterList(
                                    SingletonSeparatedList(
                                        Parameter(
                                                Identifier("obj"))
                                            .WithType(
                                                PredefinedType(
                                                    Token(SyntaxKind.ObjectKeyword))))))
                            .WithBody(
                                Block(
                                    IfStatement(
                                        IsPatternExpression(
                                            IdentifierName("obj"),
                                            ConstantPattern(
                                                LiteralExpression(
                                                    SyntaxKind.NullLiteralExpression))),
                                        ReturnStatement(
                                            LiteralExpression(
                                                SyntaxKind.FalseLiteralExpression))),
                                    IfStatement(
                                        InvocationExpression(
                                                IdentifierName("ReferenceEquals"))
                                            .WithArgumentList(
                                                ArgumentList(
                                                    SeparatedList<ArgumentSyntax>(
                                                        new SyntaxNodeOrToken[]
                                                        {
                                                            Argument(
                                                                ThisExpression()),
                                                            Token(SyntaxKind.CommaToken),
                                                            Argument(
                                                                IdentifierName("obj"))
                                                        }))),
                                        ReturnStatement(
                                            LiteralExpression(
                                                SyntaxKind.TrueLiteralExpression))),
                                    ReturnStatement(
                                        BinaryExpression(
                                            SyntaxKind.LogicalAndExpression,
                                            BinaryExpression(
                                                SyntaxKind.EqualsExpression,
                                                InvocationExpression(
                                                    MemberAccessExpression(
                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                        IdentifierName("obj"),
                                                        IdentifierName("GetType"))),
                                                InvocationExpression(
                                                    IdentifierName("GetType"))),
                                            InvocationExpression(
                                                    IdentifierName("Equals"))
                                                .WithArgumentList(
                                                    ArgumentList(
                                                        SingletonSeparatedList(
                                                            Argument(
                                                                CastExpression(
                                                                    IdentifierName(identifier),
                                                                    IdentifierName("obj")))))))))),
                        MethodDeclaration(
                                PredefinedType(
                                    Token(SyntaxKind.IntKeyword)),
                                Identifier("GetHashCode"))
                            .WithModifiers(
                                TokenList(
                                    new[]
                                    {
                                        Token(SyntaxKind.PublicKeyword),
                                        Token(SyntaxKind.OverrideKeyword)
                                    }))
                            .WithBody(
                                Block(
                                    SingletonList<StatementSyntax>(
                                        ReturnStatement(
                                            InvocationExpression(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName("_value"),
                                                    IdentifierName("GetHashCode"))))))),
                        OperatorDeclaration(
                                PredefinedType(
                                    Token(SyntaxKind.BoolKeyword)),
                                Token(SyntaxKind.EqualsEqualsToken))
                            .WithModifiers(
                                TokenList(
                                    new[]
                                    {
                                        Token(SyntaxKind.PublicKeyword),
                                        Token(SyntaxKind.StaticKeyword)
                                    }))
                            .WithParameterList(
                                ParameterList(
                                    SeparatedList<ParameterSyntax>(
                                        new SyntaxNodeOrToken[]
                                        {
                                            Parameter(
                                                    Identifier("left"))
                                                .WithType(
                                                    IdentifierName(identifier)),
                                            Token(SyntaxKind.CommaToken),
                                            Parameter(
                                                    Identifier("right"))
                                                .WithType(
                                                    IdentifierName(identifier))
                                        })))
                            .WithBody(
                                Block(
                                    SingletonList<StatementSyntax>(
                                        ReturnStatement(
                                            InvocationExpression(
                                                    IdentifierName("Equals"))
                                                .WithArgumentList(
                                                    ArgumentList(
                                                        SeparatedList<ArgumentSyntax>(
                                                            new SyntaxNodeOrToken[]
                                                            {
                                                                Argument(
                                                                    IdentifierName("left")),
                                                                Token(SyntaxKind.CommaToken),
                                                                Argument(
                                                                    IdentifierName("right"))
                                                            }))))))),
                        OperatorDeclaration(
                                PredefinedType(
                                    Token(SyntaxKind.BoolKeyword)),
                                Token(SyntaxKind.ExclamationEqualsToken))
                            .WithModifiers(
                                TokenList(
                                    new[]
                                    {
                                        Token(SyntaxKind.PublicKeyword),
                                        Token(SyntaxKind.StaticKeyword)
                                    }))
                            .WithParameterList(
                                ParameterList(
                                    SeparatedList<ParameterSyntax>(
                                        new SyntaxNodeOrToken[]
                                        {
                                            Parameter(
                                                    Identifier("left"))
                                                .WithType(
                                                    IdentifierName(identifier)),
                                            Token(SyntaxKind.CommaToken),
                                            Parameter(
                                                    Identifier("right"))
                                                .WithType(
                                                    IdentifierName(identifier))
                                        })))
                            .WithBody(
                                Block(
                                    SingletonList<StatementSyntax>(
                                        ReturnStatement(
                                            PrefixUnaryExpression(
                                                SyntaxKind.LogicalNotExpression,
                                                InvocationExpression(
                                                        IdentifierName("Equals"))
                                                    .WithArgumentList(
                                                        ArgumentList(
                                                            SeparatedList<ArgumentSyntax>(
                                                                new SyntaxNodeOrToken[]
                                                                {
                                                                    Argument(
                                                                        IdentifierName("left")),
                                                                    Token(SyntaxKind.CommaToken),
                                                                    Argument(
                                                                        IdentifierName("right"))
                                                                }))))))))
                    });
            return (baseType, members);
        }
    }
}
