using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Obviously.SemanticTypes.Generator.Modules
{
    public partial class AspNetCoreModelBinding
    {
        private static ClassDeclarationSyntax ConstructBinder(TypedConstant actualType, string identifierName)
        {
            var modelBinder = ClassDeclaration(identifierName + "ModelBinder")
                .WithModifiers(
                    TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.SealedKeyword)))
                .WithBaseList(
                    BaseList(
                        SingletonSeparatedList<BaseTypeSyntax>(
                            SimpleBaseType(
                                QualifiedName(
                                    QualifiedName(
                                        QualifiedName(
                                            QualifiedName(
                                                AliasQualifiedName(
                                                    IdentifierName(
                                                        Token(SyntaxKind.GlobalKeyword)),
                                                    IdentifierName("Microsoft")),
                                                IdentifierName("AspNetCore")),
                                            IdentifierName("Mvc")),
                                        IdentifierName("ModelBinding")),
                                    IdentifierName("IModelBinder"))))))
                .WithMembers(
                    SingletonList<MemberDeclarationSyntax>(
                        MethodDeclaration(
                                QualifiedName(
                                    QualifiedName(
                                        QualifiedName(
                                            AliasQualifiedName(
                                                IdentifierName(
                                                    Token(SyntaxKind.GlobalKeyword)),
                                                IdentifierName("System")),
                                            IdentifierName("Threading")),
                                        IdentifierName("Tasks")),
                                    IdentifierName("Task")),
                                Identifier("BindModelAsync"))
                            .WithModifiers(
                                TokenList(
                                    Token(SyntaxKind.PublicKeyword)))
                            .WithParameterList(
                                ParameterList(
                                    SingletonSeparatedList(
                                        Parameter(
                                                Identifier("bindingContext"))
                                            .WithType(
                                                QualifiedName(
                                                    QualifiedName(
                                                        QualifiedName(
                                                            QualifiedName(
                                                                AliasQualifiedName(
                                                                    IdentifierName(
                                                                        Token(SyntaxKind.GlobalKeyword)),
                                                                    IdentifierName("Microsoft")),
                                                                IdentifierName("AspNetCore")),
                                                            IdentifierName("Mvc")),
                                                        IdentifierName("ModelBinding")),
                                                    IdentifierName("ModelBindingContext"))))))
                            .WithBody(
                                Block(
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                                IdentifierName("var"))
                                            .WithVariables(
                                                SingletonSeparatedList(
                                                    VariableDeclarator(
                                                            Identifier("value"))
                                                        .WithInitializer(
                                                            EqualsValueClause(
                                                                InvocationExpression(
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                IdentifierName("bindingContext"),
                                                                                IdentifierName("ValueProvider")),
                                                                            IdentifierName("GetValue")))
                                                                    .WithArgumentList(
                                                                        ArgumentList(
                                                                            SingletonSeparatedList(
                                                                                Argument(
                                                                                    MemberAccessExpression(
                                                                                        SyntaxKind
                                                                                            .SimpleMemberAccessExpression,
                                                                                        MemberAccessExpression(
                                                                                            SyntaxKind
                                                                                                .SimpleMemberAccessExpression,
                                                                                            IdentifierName(
                                                                                                "bindingContext"),
                                                                                            IdentifierName(
                                                                                                "ModelMetadata")),
                                                                                        IdentifierName(
                                                                                            "Name"))))))))))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                                IdentifierName("var"))
                                            .WithVariables(
                                                SingletonSeparatedList(
                                                    VariableDeclarator(
                                                            Identifier("actualValue"))
                                                        .WithInitializer(
                                                            EqualsValueClause(
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    IdentifierName("value"),
                                                                    IdentifierName("FirstValue"))))))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                                IdentifierName("var"))
                                            .WithVariables(
                                                SingletonSeparatedList(
                                                    VariableDeclarator(
                                                            Identifier("concreteValue"))
                                                        .WithInitializer(
                                                            EqualsValueClause(
                                                                CastExpression(
                                                                    IdentifierName(actualType.Value.ToString()),
                                                                    InvocationExpression(
                                                                            MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                MemberAccessExpression(
                                                                                    SyntaxKind
                                                                                        .SimpleMemberAccessExpression,
                                                                                    AliasQualifiedName(
                                                                                        IdentifierName(
                                                                                            Token(SyntaxKind
                                                                                                .GlobalKeyword)),
                                                                                        IdentifierName("System")),
                                                                                    IdentifierName("Convert")),
                                                                                IdentifierName("ChangeType")))
                                                                        .WithArgumentList(
                                                                            ArgumentList(
                                                                                SeparatedList<ArgumentSyntax>(
                                                                                    new SyntaxNodeOrToken[]
                                                                                    {
                                                                                        Argument(
                                                                                            IdentifierName(
                                                                                                "actualValue")),
                                                                                        Token(SyntaxKind.CommaToken),
                                                                                        Argument(
                                                                                            TypeOfExpression(
                                                                                                PredefinedType(
                                                                                                    Token(SyntaxKind
                                                                                                        .IntKeyword))))
                                                                                    }))))))))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                                IdentifierName("var"))
                                            .WithVariables(
                                                SingletonSeparatedList(
                                                    VariableDeclarator(
                                                            Identifier("modelInstance"))
                                                        .WithInitializer(
                                                            EqualsValueClause(
                                                                ObjectCreationExpression(
                                                                        IdentifierName(identifierName))
                                                                    .WithArgumentList(
                                                                        ArgumentList(
                                                                            SingletonSeparatedList(
                                                                                Argument(
                                                                                    IdentifierName(
                                                                                        "concreteValue")))))))))),
                                    ExpressionStatement(
                                        AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("bindingContext"),
                                                IdentifierName("Result")),
                                            InvocationExpression(
                                                    MemberAccessExpression(
                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    MemberAccessExpression(
                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                        AliasQualifiedName(
                                                                            IdentifierName(
                                                                                Token(SyntaxKind.GlobalKeyword)),
                                                                            IdentifierName("Microsoft")),
                                                                        IdentifierName("AspNetCore")),
                                                                    IdentifierName("Mvc")),
                                                                IdentifierName("ModelBinding")),
                                                            IdentifierName("ModelBindingResult")),
                                                        IdentifierName("Success")))
                                                .WithArgumentList(
                                                    ArgumentList(
                                                        SingletonSeparatedList(
                                                            Argument(
                                                                IdentifierName("modelInstance"))))))),
                                    ReturnStatement(
                                        MemberAccessExpression(
                                            SyntaxKind.SimpleMemberAccessExpression,
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    MemberAccessExpression(
                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                        AliasQualifiedName(
                                                            IdentifierName(
                                                                Token(SyntaxKind.GlobalKeyword)),
                                                            IdentifierName("System")),
                                                        IdentifierName("Threading")),
                                                    IdentifierName("Tasks")),
                                                IdentifierName("Task")),
                                            IdentifierName("CompletedTask")))))));
            return modelBinder;
        }
    }
}
