using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Obviously.SemanticTypes.Generator.Modules
{
    public partial class AspNetCoreModelBinding
    {
        private static ClassDeclarationSyntax ConstructBinder(TypedConstant actualType, string identifierName)
        {
            var className = PrefixForSubClasses + "ModelBinder";
            var modelBinder = ClassDeclaration(className)
                .WithModifiers(
                    TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.SealedKeyword)))
                .WithBaseList(
                    BaseList(
                        SingletonSeparatedList<BaseTypeSyntax>(
                            SimpleBaseType(
                                QualifiedName(
                                    QualifiedName(
                                        QualifiedName(
                                            QualifiedName(
                                                AliasQualifiedName(
                                                    IdentifierName(
                                                        Token(SyntaxKind.GlobalKeyword)),
                                                    IdentifierName("Microsoft")),
                                                IdentifierName("AspNetCore")),
                                            IdentifierName("Mvc")),
                                        IdentifierName("ModelBinding")),
                                    IdentifierName("IModelBinder"))))))
                .WithMembers(
                    List(
                        new MemberDeclarationSyntax[]{
                            FieldDeclaration(
                                VariableDeclaration(
                                    QualifiedName(
                                        QualifiedName(
                                            QualifiedName(
                                                QualifiedName(
                                                    AliasQualifiedName(
                                                        IdentifierName(
                                                            Token(SyntaxKind.GlobalKeyword)),
                                                        IdentifierName("Microsoft")),
                                                    IdentifierName("AspNetCore")),
                                                IdentifierName("Mvc")),
                                            IdentifierName("ModelBinding")),
                                        IdentifierName("ModelMetadata")))
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator(
                                            Identifier("_metadataForType")))))
                            .WithModifiers(
                                TokenList(Token(SyntaxKind.PrivateKeyword), Token(SyntaxKind.ReadOnlyKeyword))),
                            FieldDeclaration(
                                VariableDeclaration(
                                    QualifiedName(
                                        QualifiedName(
                                            QualifiedName(
                                                QualifiedName(
                                                    AliasQualifiedName(
                                                        IdentifierName(
                                                            Token(SyntaxKind.GlobalKeyword)),
                                                        IdentifierName("Microsoft")),
                                                    IdentifierName("AspNetCore")),
                                                IdentifierName("Mvc")),
                                            IdentifierName("ModelBinding")),
                                        IdentifierName("IModelBinder")))
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator(
                                            Identifier("_specificBinder")))))
                            .WithModifiers(
                                TokenList(Token(SyntaxKind.PrivateKeyword), Token(SyntaxKind.ReadOnlyKeyword))),
                            ConstructorDeclaration(
                                Identifier(className))
                            .WithModifiers(
                                TokenList(
                                    Token(SyntaxKind.PublicKeyword)))
                            .WithParameterList(
                                ParameterList(
                                    SeparatedList<ParameterSyntax>(
                                        new SyntaxNodeOrToken[]{
                                            Parameter(
                                                Identifier("metadataForType"))
                                            .WithType(
                                                QualifiedName(
                                                    QualifiedName(
                                                        QualifiedName(
                                                            QualifiedName(
                                                                AliasQualifiedName(
                                                                    IdentifierName(
                                                                        Token(SyntaxKind.GlobalKeyword)),
                                                                    IdentifierName("Microsoft")),
                                                                IdentifierName("AspNetCore")),
                                                            IdentifierName("Mvc")),
                                                        IdentifierName("ModelBinding")),
                                                    IdentifierName("ModelMetadata"))),
                                            Token(SyntaxKind.CommaToken),
                                            Parameter(
                                                Identifier("specificBinder"))
                                            .WithType(
                                                QualifiedName(
                                                    QualifiedName(
                                                        QualifiedName(
                                                            QualifiedName(
                                                                AliasQualifiedName(
                                                                    IdentifierName(
                                                                        Token(SyntaxKind.GlobalKeyword)),
                                                                    IdentifierName("Microsoft")),
                                                                IdentifierName("AspNetCore")),
                                                            IdentifierName("Mvc")),
                                                        IdentifierName("ModelBinding")),
                                                    IdentifierName("IModelBinder")))})))
                            .WithBody(
                                Block(
                                    ExpressionStatement(
                                        AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            IdentifierName("_metadataForType"),
                                            IdentifierName("metadataForType"))),
                                    ExpressionStatement(
                                        AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            IdentifierName("_specificBinder"),
                                            IdentifierName("specificBinder"))))),
                            MethodDeclaration(
                                QualifiedName(
                                    QualifiedName(
                                        QualifiedName(
                                            AliasQualifiedName(
                                                IdentifierName(
                                                    Token(SyntaxKind.GlobalKeyword)),
                                                IdentifierName("System")),
                                            IdentifierName("Threading")),
                                        IdentifierName("Tasks")),
                                    IdentifierName("Task")),
                                Identifier("BindModelAsync"))
                            .WithModifiers(
                                TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.AsyncKeyword)))
                            .WithParameterList(
                                ParameterList(
                                    SingletonSeparatedList(
                                        Parameter(
                                            Identifier("bindingContext"))
                                        .WithType(
                                            QualifiedName(
                                                QualifiedName(
                                                    QualifiedName(
                                                        QualifiedName(
                                                            AliasQualifiedName(
                                                                IdentifierName(
                                                                    Token(SyntaxKind.GlobalKeyword)),
                                                                IdentifierName("Microsoft")),
                                                            IdentifierName("AspNetCore")),
                                                        IdentifierName("Mvc")),
                                                    IdentifierName("ModelBinding")),
                                                IdentifierName("ModelBindingContext"))))))
                            .WithBody(
                                Block(
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                            IdentifierName("var"))
                                        .WithVariables(
                                            SingletonSeparatedList(
                                                VariableDeclarator(
                                                    Identifier("value"))
                                                .WithInitializer(
                                                    EqualsValueClause(
                                                        InvocationExpression(
                                                            MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    IdentifierName("bindingContext"),
                                                                    IdentifierName("ValueProvider")),
                                                                IdentifierName("GetValue")))
                                                        .WithArgumentList(
                                                            ArgumentList(
                                                                SingletonSeparatedList(
                                                                    Argument(
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            IdentifierName("bindingContext"),
                                                                            IdentifierName("ModelName"))))))))))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                            IdentifierName("var"))
                                        .WithVariables(
                                            SingletonSeparatedList(
                                                VariableDeclarator(
                                                    Identifier("actualValue"))
                                                .WithInitializer(
                                                    EqualsValueClause(
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            IdentifierName("value"),
                                                            IdentifierName("FirstValue"))))))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                            IdentifierName(actualType.Value.ToString()))
                                        .WithVariables(
                                            SingletonSeparatedList(
                                                VariableDeclarator(
                                                    Identifier("modelBindingResult"))))),
                                    UsingStatement(
                                        Block(
                                            LocalDeclarationStatement(
                                                VariableDeclaration(
                                                    IdentifierName("var"))
                                                .WithVariables(
                                                    SingletonSeparatedList(
                                                        VariableDeclarator(
                                                            Identifier("newBindingContext"))
                                                        .WithInitializer(
                                                            EqualsValueClause(
                                                                InvocationExpression(
                                                                    MemberAccessExpression(
                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                MemberAccessExpression(
                                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                                    MemberAccessExpression(
                                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                                        AliasQualifiedName(
                                                                                            IdentifierName(
                                                                                                Token(SyntaxKind.GlobalKeyword)),
                                                                                            IdentifierName("Microsoft")),
                                                                                        IdentifierName("AspNetCore")),
                                                                                    IdentifierName("Mvc")),
                                                                                IdentifierName("ModelBinding")),
                                                                            IdentifierName("DefaultModelBindingContext")),
                                                                        IdentifierName("CreateBindingContext")))
                                                                .WithArgumentList(
                                                                    ArgumentList(
                                                                        SeparatedList<ArgumentSyntax>(
                                                                            new SyntaxNodeOrToken[]{
                                                                                Argument(
                                                                                    MemberAccessExpression(
                                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                                        IdentifierName("bindingContext"),
                                                                                        IdentifierName("ActionContext"))),
                                                                                Token(SyntaxKind.CommaToken),
                                                                                Argument(
                                                                                    MemberAccessExpression(
                                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                                        IdentifierName("bindingContext"),
                                                                                        IdentifierName("ValueProvider"))),
                                                                                Token(SyntaxKind.CommaToken),
                                                                                Argument(
                                                                                    IdentifierName("_metadataForType")),
                                                                                Token(SyntaxKind.CommaToken),
                                                                                Argument(
                                                                                    LiteralExpression(
                                                                                        SyntaxKind.NullLiteralExpression)),
                                                                                Token(SyntaxKind.CommaToken),
                                                                                Argument(
                                                                                    MemberAccessExpression(
                                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                                        IdentifierName("bindingContext"),
                                                                                        IdentifierName("ModelName")))})))))))),
                                            ExpressionStatement(
                                                AwaitExpression(
                                                    InvocationExpression(
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            InvocationExpression(
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    IdentifierName("_specificBinder"),
                                                                    IdentifierName("BindModelAsync")))
                                                            .WithArgumentList(
                                                                ArgumentList(
                                                                    SingletonSeparatedList(
                                                                        Argument(
                                                                            IdentifierName("newBindingContext"))))),
                                                            IdentifierName("ConfigureAwait")))
                                                    .WithArgumentList(
                                                        ArgumentList(
                                                            SingletonSeparatedList(
                                                                Argument(
                                                                    LiteralExpression(
                                                                        SyntaxKind.FalseLiteralExpression))))))),
                                            ExpressionStatement(
                                                AssignmentExpression(
                                                    SyntaxKind.SimpleAssignmentExpression,
                                                    IdentifierName("modelBindingResult"),
                                                    CastExpression(
                                                        IdentifierName(actualType.Value.ToString()),
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                IdentifierName("newBindingContext"),
                                                                IdentifierName("Result")),
                                                            IdentifierName("Model")))))))
                                    .WithExpression(
                                        InvocationExpression(
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("bindingContext"),
                                                IdentifierName("EnterNestedScope")))
                                        .WithArgumentList(
                                            ArgumentList(
                                                SeparatedList<ArgumentSyntax>(
                                                    new SyntaxNodeOrToken[]{
                                                        Argument(
                                                            IdentifierName("_metadataForType")),
                                                        Token(SyntaxKind.CommaToken),
                                                        Argument(
                                                            LiteralExpression(
                                                                SyntaxKind.StringLiteralExpression,
                                                                Literal("Value"))),
                                                        Token(SyntaxKind.CommaToken),
                                                        Argument(
                                                            MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                IdentifierName("bindingContext"),
                                                                IdentifierName("ModelName"))),
                                                        Token(SyntaxKind.CommaToken),
                                                        Argument(
                                                            IdentifierName("actualValue"))})))),
                                    LocalDeclarationStatement(
                                        VariableDeclaration(
                                            IdentifierName("var"))
                                        .WithVariables(
                                            SingletonSeparatedList(
                                                VariableDeclarator(
                                                    Identifier("modelInstance"))
                                                .WithInitializer(
                                                    EqualsValueClause(
                                                        ObjectCreationExpression(
                                                            IdentifierName(identifierName))
                                                        .WithArgumentList(
                                                            ArgumentList(
                                                                SingletonSeparatedList(
                                                                    Argument(
                                                                        IdentifierName("modelBindingResult")))))))))),
                                    ExpressionStatement(
                                        AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("bindingContext"),
                                                IdentifierName("Result")),
                                            InvocationExpression(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    MemberAccessExpression(
                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    AliasQualifiedName(
                                                                        IdentifierName(
                                                                            Token(SyntaxKind.GlobalKeyword)),
                                                                        IdentifierName("Microsoft")),
                                                                    IdentifierName("AspNetCore")),
                                                                IdentifierName("Mvc")),
                                                            IdentifierName("ModelBinding")),
                                                        IdentifierName("ModelBindingResult")),
                                                    IdentifierName("Success")))
                                            .WithArgumentList(
                                                ArgumentList(
                                                    SingletonSeparatedList(
                                                        Argument(
                                                            IdentifierName("modelInstance")))))))))}));
            return modelBinder;
        }
    }
}
